import type { PageType, StoreTemplate } from "./schema";
import { slugify, validateExportTemplate } from "./export-utils";
import { createZip, type ZipFile } from "./zip";

export function createNextProjectFiles(template: StoreTemplate): ZipFile[] {
  const validatedTemplate = validateExportTemplate(template);
  const projectName = slugify(validatedTemplate.name);

  return [
    { path: `${projectName}/package.json`, content: renderPackageJson(projectName) },
    { path: `${projectName}/next.config.ts`, content: "import type { NextConfig } from 'next';\n\nconst nextConfig: NextConfig = {};\n\nexport default nextConfig;\n" },
    { path: `${projectName}/tsconfig.json`, content: renderTsConfig() },
    { path: `${projectName}/next-env.d.ts`, content: "/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n\n// This file is generated by Next.js.\n" },
    { path: `${projectName}/README.md`, content: renderReadme(validatedTemplate) },
    { path: `${projectName}/app/globals.css`, content: renderGlobalsCss(validatedTemplate) },
    { path: `${projectName}/app/layout.tsx`, content: renderLayout(validatedTemplate) },
    { path: `${projectName}/app/page.tsx`, content: renderRoutePage("home") },
    { path: `${projectName}/app/collection/page.tsx`, content: renderRoutePage("collection") },
    { path: `${projectName}/app/product/page.tsx`, content: renderRoutePage("product") },
    { path: `${projectName}/app/cart/page.tsx`, content: renderRoutePage("cart") },
    { path: `${projectName}/app/checkout/page.tsx`, content: renderRoutePage("checkout") },
    { path: `${projectName}/app/about/page.tsx`, content: renderRoutePage("about") },
    { path: `${projectName}/app/contact/page.tsx`, content: renderRoutePage("contact") },
    { path: `${projectName}/components/storefront.tsx`, content: renderStorefrontComponent() },
    { path: `${projectName}/data/template.ts`, content: renderTemplateData(validatedTemplate) },
  ];
}

export function downloadNextProject(template: StoreTemplate) {
  const validatedTemplate = validateExportTemplate(template);
  const blob = new Blob([createZip(createNextProjectFiles(validatedTemplate))], { type: "application/zip" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.download = `${slugify(validatedTemplate.name)}-next-storefront.zip`;
  link.click();
  URL.revokeObjectURL(url);
}

function renderPackageJson(projectName: string) {
  return `${JSON.stringify(
    {
      name: projectName,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "eslint",
      },
      dependencies: {
        next: "16.2.6",
        react: "19.2.4",
        "react-dom": "19.2.4",
      },
      devDependencies: {
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        eslint: "^9",
        "eslint-config-next": "16.2.6",
        typescript: "^5",
      },
    },
    null,
    2,
  )}\n`;
}

function renderTsConfig() {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "react-jsx",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2,
  )}\n`;
}

function renderReadme(template: StoreTemplate) {
  return `# ${template.name}

Generated by Store Templater.

## Run locally

\`\`\`bash
pnpm install
pnpm dev
\`\`\`

This export is local/static-first. It includes browsable pages and a mock cart flow, but it is not connected to a backend, payment provider, or inventory system yet.
`;
}

function renderLayout(template: StoreTemplate) {
  return `import { StorefrontProvider } from '@/components/storefront';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: ${JSON.stringify(template.name)},
  description: 'Generated Store Templater storefront',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StorefrontProvider>{children}</StorefrontProvider>
      </body>
    </html>
  );
}
`;
}

function renderRoutePage(type: PageType) {
  return `import { StorefrontApp } from '@/components/storefront';

export default function Page() {
  return <StorefrontApp pageType="${type}" />;
}
`;
}

function renderTemplateData(template: StoreTemplate) {
  return `export const template = ${JSON.stringify(template, null, 2)} as const;
`;
}

function renderGlobalsCss(template: StoreTemplate) {
  const theme = template.theme;

  return `:root {
  --store-canvas: ${theme.colors.canvas};
  --store-surface: ${theme.colors.surface};
  --store-text: ${theme.colors.text};
  --store-muted: ${theme.colors.muted};
  --store-primary: ${theme.colors.primary};
  --store-secondary: ${theme.colors.secondary};
  --store-accent: ${theme.colors.accent};
  --store-border: ${theme.colors.border};
  --store-radius: ${theme.layout.radius}px;
  --store-max-width: ${theme.layout.maxWidth}px;
  --store-heading-scale: ${theme.typography.scale === "editorial" ? "1.14" : theme.typography.scale === "compact" ? "0.9" : "1"};
}

* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--store-canvas);
  color: var(--store-text);
  font-family: ${theme.typography.body.includes("serif") ? "Georgia, serif" : "Inter, Arial, sans-serif"};
}
a { color: inherit; text-decoration: none; }
button, input { font: inherit; }
.wrap { max-width: var(--store-max-width); margin: 0 auto; padding: 0 28px; }
.section { padding: 56px 0; }
.compact { padding: 28px 0; }
.spacious { padding: 86px 0; }
.surface { background: var(--store-surface); }
.primary { background: var(--store-primary); color: white; }
.dark { background: var(--store-text); color: white; }
.announcement { background: var(--store-text); color: white; padding: 10px 18px; text-align: center; font-size: 13px; font-weight: 700; }
.header { position: sticky; top: 0; z-index: 10; border-bottom: 1px solid var(--store-border); background: color-mix(in srgb, var(--store-surface) 94%, transparent); backdrop-filter: blur(12px); }
.headerInner { min-height: 68px; display: flex; align-items: center; justify-content: space-between; gap: 28px; }
.logo { font-weight: 900; letter-spacing: .16em; }
.nav { display: flex; gap: 24px; color: var(--store-muted); font-size: 14px; font-weight: 650; }
.pill { display: inline-flex; border: 1px solid var(--store-border); border-radius: 999px; padding: 9px 15px; background: var(--store-surface); font-size: 13px; font-weight: 750; }
h1, h2, h3 { margin: 0; line-height: 1.05; letter-spacing: 0; }
h1 { font-size: calc(56px * var(--store-heading-scale)); }
h2 { font-size: calc(34px * var(--store-heading-scale)); }
p { margin: 0; }
.eyebrow { color: var(--store-primary); text-transform: uppercase; letter-spacing: .18em; font-size: 12px; font-weight: 900; }
.eyebrowSmall { font-size: 11px; letter-spacing: .14em; text-transform: uppercase; }
.muted { color: var(--store-muted); }
.button { display: inline-flex; align-items: center; justify-content: center; border: 0; border-radius: var(--store-radius); background: var(--store-primary); color: white; padding: 13px 20px; font-weight: 900; box-shadow: 0 14px 28px rgb(15 23 42 / .12); cursor: pointer; }
.button.dark { background: var(--store-text); }
.button.outline { border: 1px solid var(--store-border); background: var(--store-surface); color: var(--store-text); }
.button.full { width: 100%; margin-top: 20px; }
.heroGrid { display: grid; grid-template-columns: .92fr 1.08fr; gap: 48px; align-items: center; }
.heroGrid.spotlight { grid-template-columns: 1.12fr .88fr; }
.heroCentered { text-align: center; }
.heroCentered .heroCopy { margin-left: auto; margin-right: auto; }
.heroCopy, .sectionCopy { margin-top: 18px; max-width: 620px; color: var(--store-muted); font-size: 18px; line-height: 1.7; }
.actions, .chips { display: flex; gap: 12px; flex-wrap: wrap; margin-top: 28px; }
.heroCentered .actions { justify-content: center; }
.details { margin-top: 28px; display: grid; gap: 10px; font-weight: 700; }
.proofRow { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 14px; color: var(--store-muted); font-size: 12px; font-weight: 800; }
.proofRow span:first-child { border-radius: 999px; background: var(--store-surface); color: var(--store-primary); padding: 6px 10px; }
.trustGrid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 10px; margin-top: 24px; }
.trustGrid span { border: 1px solid var(--store-border); border-radius: var(--store-radius); background: var(--store-surface); padding: 12px; text-align: center; font-size: 12px; font-weight: 900; }
.heroCard { position: relative; min-height: 480px; overflow: hidden; border: 1px solid var(--store-border); border-radius: calc(var(--store-radius) + 12px); background: var(--store-surface); box-shadow: 0 28px 60px rgb(15 23 42 / .14); }
.heroArt { position: absolute; inset: 18px; border-radius: var(--store-radius); background: linear-gradient(135deg, var(--store-secondary), var(--store-accent)); }
.floatingCard { position: absolute; left: 34px; right: 34px; bottom: 34px; border-radius: var(--store-radius); background: rgb(255 255 255 / .86); color: var(--store-text); padding: 22px; box-shadow: 0 20px 45px rgb(15 23 42 / .16); }
.grid { display: grid; gap: 22px; }
.cols3 { grid-template-columns: repeat(3, minmax(0, 1fr)); }
.cols4 { grid-template-columns: repeat(4, minmax(0, 1fr)); }
.productGrid { margin-top: 32px; }
.productGrid.grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 22px; }
.productGrid.editorial { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 22px; }
.productGrid.editorial > *:first-child { grid-column: span 2; }
.productGrid.compact { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 12px; }
.card { position: relative; border: 1px solid var(--store-border); border-radius: calc(var(--store-radius) + 8px); background: var(--store-surface); overflow: hidden; box-shadow: 0 14px 28px rgb(15 23 42 / .06); }
.card { transition: transform .18s ease, box-shadow .18s ease, border-color .18s ease; }
.card:hover { transform: translateY(-3px); border-color: color-mix(in srgb, var(--store-primary) 35%, var(--store-border)); box-shadow: 0 20px 42px rgb(15 23 42 / .1); }
.cardBody { padding: 18px; }
.card.compact .cardBody { padding: 12px; }
.card.compact h3 { font-size: 15px; }
.badge { position: absolute; left: 14px; top: 14px; z-index: 2; border-radius: 999px; background: rgb(255 255 255 / .92); color: var(--store-text); padding: 7px 11px; font-size: 12px; font-weight: 900; box-shadow: 0 8px 20px rgb(15 23 42 / .1); }
.productImage { aspect-ratio: 4 / 5; background-color: #f8fafc; background-position: center; background-repeat: no-repeat; background-size: cover; }
.card.compact .productImage { aspect-ratio: 1; }
.productImage.large { border: 1px solid var(--store-border); border-radius: calc(var(--store-radius) + 10px); }
.quickAdd { position: absolute; right: 14px; bottom: 14px; border: 0; border-radius: 999px; background: var(--store-text); color: white; padding: 9px 13px; font-size: 12px; font-weight: 800; cursor: pointer; }
.price { margin-top: 16px; font-size: 26px; font-weight: 900; }
.priceSmall { margin-top: 14px; font-weight: 900; }
.collectionLayout { display: grid; grid-template-columns: 220px minmax(0, 1fr); gap: 24px; margin-top: 30px; }
.filters { display: grid; align-content: start; gap: 10px; }
.filterButton { display: flex; justify-content: space-between; gap: 12px; border: 1px solid var(--store-border); border-radius: var(--store-radius); background: var(--store-canvas); padding: 13px 14px; color: var(--store-text); font-weight: 800; }
.cartLines, .stack { display: grid; gap: 14px; margin-top: 24px; }
.cartLine { display: grid; grid-template-columns: 88px 1fr auto; gap: 16px; align-items: center; padding: 14px; border: 1px solid var(--store-border); border-radius: var(--store-radius); background: var(--store-surface); }
.summary { border: 1px solid var(--store-border); border-radius: calc(var(--store-radius) + 8px); background: var(--store-surface); padding: 22px; }
.line, .total { display: flex; justify-content: space-between; gap: 18px; padding: 10px 0; color: var(--store-muted); }
.total { margin-top: 14px; border-top: 1px solid var(--store-border); padding-top: 18px; color: var(--store-text); }
.formMock { display: grid; gap: 14px; margin-top: 28px; }
.newsletter { display: grid; grid-template-columns: 1fr auto; gap: 18px; align-items: center; border: 1px solid var(--store-border); border-radius: calc(var(--store-radius) + 8px); background: var(--store-surface); padding: 24px; }
.footer { padding: 46px 0; background: var(--store-text); color: white; }
.footerLinks { display: flex; gap: 22px; flex-wrap: wrap; margin-top: 20px; color: rgb(255 255 255 / .72); }
@media (max-width: 760px) {
  .wrap { padding: 0 20px; }
  .section { padding: 42px 0; }
  .nav { display: none; }
  h1 { font-size: calc(38px * var(--store-heading-scale)); }
  h2 { font-size: calc(28px * var(--store-heading-scale)); }
  .heroGrid, .heroGrid.spotlight, .cols3, .cols4, .newsletter, .collectionLayout, .trustGrid, .productGrid.grid, .productGrid.editorial { grid-template-columns: 1fr; }
  .productGrid.compact { grid-template-columns: repeat(2, minmax(0, 1fr)); }
  .productGrid.editorial > *:first-child { grid-column: span 1; }
  .heroCard { min-height: 320px; }
  .floatingCard { left: 20px; right: 20px; bottom: 20px; }
  .cartLine { grid-template-columns: 72px 1fr; }
}
`;
}

function renderStorefrontComponent() {
  return `"use client";

import Link from 'next/link';
import { createContext, useContext, useState } from 'react';
import { template } from '@/data/template';

type PageType = 'home' | 'collection' | 'product' | 'cart' | 'checkout' | 'about' | 'contact';
type Template = typeof template;
type TemplatePage = Template['pages'][number];
type TemplateSection = TemplatePage['sections'][number];
type Product = Template['products'][number];
type CartItem = { productId: string; quantity: number };
type StorefrontState = {
  activeProductId: string;
  addToCart: (productId: string) => void;
  cartCount: number;
  cartItems: CartItem[];
  setActiveProductId: (productId: string) => void;
};

const StorefrontContext = createContext<StorefrontState | null>(null);

const pagePaths: Record<PageType, string> = {
  home: '/',
  collection: '/collection',
  product: '/product',
  cart: '/cart',
  checkout: '/checkout',
  about: '/about',
  contact: '/contact',
};

export function StorefrontProvider({ children }: { children: React.ReactNode }) {
  const [activeProductId, setActiveProductId] = useState(template.products[0]?.id ?? '');
  const [cartItems, setCartItems] = useState<CartItem[]>([]);
  const cartCount = cartItems.reduce((total, item) => total + item.quantity, 0);

  function addToCart(productId: string) {
    setCartItems((current) => {
      const existing = current.find((item) => item.productId === productId);
      if (existing) {
        return current.map((item) => item.productId === productId ? { ...item, quantity: item.quantity + 1 } : item);
      }
      return [...current, { productId, quantity: 1 }];
    });
  }

  return (
    <StorefrontContext.Provider value={{ activeProductId, addToCart, cartCount, cartItems, setActiveProductId }}>
      {children}
    </StorefrontContext.Provider>
  );
}

export function StorefrontApp({ pageType }: { pageType: PageType }) {
  const pages = template.pages.filter((page) => page.status === 'published');
  const page = pages.find((candidate) => candidate.type === pageType) ?? pages[0] ?? template.pages[0];
  const state = useContext(StorefrontContext);

  if (!state) {
    throw new Error('StorefrontApp must be rendered inside StorefrontProvider.');
  }

  return (
    <main className="storefront">
      {(page.sections as TemplateSection[])
        .filter((section) => section.enabled)
        .map((section) => (
          <Section
            activeProductId={state.activeProductId}
            addToCart={state.addToCart}
            cartCount={state.cartCount}
            cartItems={state.cartItems}
            key={section.id}
            page={page}
            pages={pages}
            section={section}
            setActiveProductId={state.setActiveProductId}
          />
        ))}
    </main>
  );
}

function Section({
  activeProductId,
  addToCart,
  cartCount,
  cartItems,
  pages,
  section,
  setActiveProductId,
}: {
  activeProductId: string;
  addToCart: (productId: string) => void;
  cartCount: number;
  cartItems: CartItem[];
  page: TemplatePage;
  pages: TemplatePage[];
  section: TemplateSection;
  setActiveProductId: (productId: string) => void;
}) {
  const settings = section.settings as Record<string, unknown>;
  const productPage = pathFor(pages, 'product');
  const primaryButtonClass = buttonClass(settings);

  if (section.type === 'announcement') {
    return <div className="announcement">{String(settings.text ?? '')}</div>;
  }

  if (section.type === 'header') {
    const navLinks = headerNavLinks(pages, settings);
    const cartLabel = textSetting(settings.labelCart, 'Cart');

    return (
      <header className="header">
        <div className="wrap headerInner">
          <Link className="logo" href="/">{String(settings.logo ?? template.name)}</Link>
          <nav className="nav">
            {navLinks.map((link) => (
              link.href.startsWith('/') ? (
                <Link href={link.href} key={link.id}>{link.label}</Link>
              ) : (
                <a href={link.href} key={link.id} rel="noreferrer" target="_blank">{link.label}</a>
              )
            ))}
          </nav>
          {settings.showCartLink === false ? null : <Link className="pill" href={pathFor(pages, 'cart')}>{cartLabel} {cartCount}</Link>}
        </div>
      </header>
    );
  }

  if (section.type === 'hero') {
    return <HeroSection pages={pages} primaryButtonClass={primaryButtonClass} section={section} />;
  }

  if (section.type === 'categoryStrip') {
    return (
      <section className={sectionClass(section, 'compact surface')}>
        <div className="wrap grid cols4">
          {arraySetting(settings.categories).map((category) => (
            <Link className="card cardBody" href={pathFor(pages, 'collection')} key={category}>
              <h3>{category}</h3>
              <p className="muted">Shop collection</p>
            </Link>
          ))}
        </div>
      </section>
    );
  }

  if (section.type === 'productGrid' || section.type === 'collectionGrid') {
    const isCollection = section.type === 'collectionGrid';
    const products = template.products.slice(0, numberSetting(settings.productCount, section.type === 'collectionGrid' ? 6 : 3));
    const filters = arraySetting(settings.filters);
    const showFilters = settings.showFilters !== false && filters.length > 0;
    const layout = styleSetting(settings.productGridLayout, 'grid');
    return (
      <section className={sectionClass(section, 'surface')}>
        <div className="wrap">
          <p className="eyebrow">{String(settings.eyebrow ?? 'Selected for you')}</p>
          <h2>{String(settings.title ?? 'Products')}</h2>
          {settings.description ? <p className="sectionCopy">{String(settings.description)}</p> : null}
          <div className={isCollection && showFilters ? 'collectionLayout' : 'productGrid'}>
            {isCollection && showFilters ? (
              <aside className="filters">
                <p className="eyebrowSmall muted">Filter</p>
                {filters.map((filter) => <button className="filterButton" key={filter} type="button"><span>{filter}</span><span>Any</span></button>)}
              </aside>
            ) : null}
            <div className={'productGrid ' + layout}>
              {products.map((product) => (
                <ProductCard
                  addToCart={addToCart}
                  compact={layout === 'compact'}
                  href={productPage}
                  key={product.id}
                  product={product}
                  setActiveProductId={setActiveProductId}
                />
              ))}
            </div>
          </div>
        </div>
      </section>
    );
  }

  if (section.type === 'productDetail') {
    const product = template.products.find((candidate) => candidate.id === activeProductId) ?? template.products[0];
    const socialProof = arraySetting(settings.socialProof).length > 0 ? arraySetting(settings.socialProof) : ['★★★★★ 4.9', '128 reviews', 'Low stock'];
    const trustItems = arraySetting(settings.trustItems).length > 0 ? arraySetting(settings.trustItems) : ['Secure checkout', 'Free returns', 'Ships tracked'];
    return (
      <section className={sectionClass(section, '')}>
        <div className="wrap heroGrid">
          <ProductImage product={product} large />
          <div>
            <p className="eyebrow">{String(settings.badge ?? 'Featured')}</p>
            <h1>{product?.name ?? String(settings.title ?? 'Product')}</h1>
            <p className="price">\${product?.price ?? 0}</p>
            <div className="proofRow">{socialProof.map((proof) => <span key={proof}>{proof}</span>)}</div>
            <p className="heroCopy">{String(settings.subtitle ?? '')}</p>
            <div className="chips">{arraySetting(settings.variants).map((variant) => <span className="pill" key={variant}>{variant}</span>)}</div>
            <Link
              className={primaryButtonClass}
              href={pathFor(pages, 'cart')}
              onClick={() => product ? addToCart(product.id) : undefined}
            >
              Add to cart
            </Link>
            <div className="details">{arraySetting(settings.details).map((detail) => <p key={detail}>{detail}</p>)}</div>
            <div className="trustGrid">{trustItems.map((item) => <span key={item}>{item}</span>)}</div>
          </div>
        </div>
      </section>
    );
  }

  if (section.type === 'cartSummary') {
    const entries = cartItems.map((item) => ({ item, product: template.products.find((product) => product.id === item.productId) })).filter((entry): entry is { item: CartItem; product: Product } => Boolean(entry.product));
    const subtotal = entries.reduce((total, entry) => total + entry.product.price * entry.item.quantity, 0);
    return (
      <section className={sectionClass(section, '')}>
        <div className="wrap heroGrid">
          <div>
            <h1>{String(settings.title ?? 'Cart')}</h1>
            <p className="muted">{String(settings.note ?? '')}</p>
            <div className="cartLines">
              {entries.length > 0 ? entries.map(({ item, product }) => (
                <article className="cartLine" key={product.id}>
                  <ProductImage product={product} />
                  <div><h3>{product.name}</h3><p className="muted">{product.category} · Qty {item.quantity}</p></div>
                  <strong>\${product.price * item.quantity}</strong>
                </article>
              )) : (
                <div className="card cardBody">
                  <h3>Your cart is empty</h3>
                  <p className="muted">Add a product from the collection or product page to test the flow.</p>
                  <Link className="button" href={pathFor(pages, 'collection')}>Browse products</Link>
                </div>
              )}
            </div>
          </div>
          <aside className="summary">
            <h2>Order summary</h2>
            <SummaryRow label="Subtotal" value={'$' + subtotal} />
            <SummaryRow label="Estimated tax" value="$12" />
            <div className="total"><span>Total</span><strong>\${subtotal + 12}</strong></div>
            {entries.length > 0 ? (
              <Link className="button full" href={pathFor(pages, 'checkout')}>Checkout</Link>
            ) : (
              <Link className="button full outline" href={pathFor(pages, 'collection')}>Continue shopping</Link>
            )}
          </aside>
        </div>
      </section>
    );
  }

  if (section.type === 'checkoutSummary') {
    const firstProduct = template.products[0];
    return (
      <section className={sectionClass(section, 'surface')}>
        <div className="wrap heroGrid">
          <div>
            <h1>{String(settings.title ?? 'Checkout')}</h1>
            <p className="muted">{String(settings.subtitle ?? '')}</p>
            <div className="formMock">
              {['Email address', 'Shipping address', 'Delivery method', 'Payment details'].map((field) => <div className="pill" key={field}>{field}</div>)}
              <button className={primaryButtonClass} type="button">Continue</button>
            </div>
          </div>
          <aside className="summary">
            <h2>Order</h2>
            {firstProduct ? <ProductCard addToCart={addToCart} href={productPage} product={firstProduct} setActiveProductId={setActiveProductId} compact /> : null}
          </aside>
        </div>
      </section>
    );
  }

  if (section.type === 'promoTiles') {
    return <SimpleListSection items={arraySetting(settings.tiles)} section={section} title={String(settings.title ?? 'Featured edits')} />;
  }

  if (section.type === 'reviews') {
    return <SimpleListSection items={arraySetting(settings.reviews)} section={section} title={String(settings.title ?? 'Reviews')} />;
  }

  if (section.type === 'trustBand' || section.type === 'featureBand') {
    return <SimpleListSection items={arraySetting(section.type === 'trustBand' ? settings.items : settings.points)} section={section} title={String(settings.title ?? 'Why shop with us')} />;
  }

  if (section.type === 'faq') {
    return (
      <section className={sectionClass(section, '')}>
        <div className="wrap">
          <h2>{String(settings.title ?? 'FAQ')}</h2>
          <div className="stack">{arraySetting(settings.questions).map((question, index) => <details className="card cardBody" key={question} open={index === 0}><summary>{question}</summary><p className="muted">This answer can be customized in Store Templater.</p></details>)}</div>
        </div>
      </section>
    );
  }

  if (section.type === 'newsletter') {
    return (
      <section className={sectionClass(section, '')}>
        <div className="wrap newsletter"><h2>{String(settings.title ?? 'Subscribe')}</h2><button className="button dark" type="button">{String(settings.cta ?? 'Subscribe')}</button></div>
      </section>
    );
  }

  return (
    <footer className="footer">
      <div className="wrap">
        <h3>{template.name}</h3>
        <div className="footerLinks">{pages.map((candidate) => <Link href={pagePaths[candidate.type as PageType] ?? '/'} key={candidate.id}>{candidate.name}</Link>)}</div>
      </div>
    </footer>
  );
}

function ProductCard({
  addToCart,
  compact,
  href,
  product,
  setActiveProductId,
}: {
  addToCart: (productId: string) => void;
  compact?: boolean;
  href: string;
  product: Product;
  setActiveProductId: (productId: string) => void;
}) {
  return (
    <article className={compact ? 'productCompact' : 'card'}>
      {product.badge ? <span className="badge">{product.badge}</span> : null}
      <Link href={href} onClick={() => setActiveProductId(product.id)}>
        <ProductImage product={product} />
        <div className="cardBody">
          <p className="muted eyebrowSmall">{product.category}</p>
          <h3>{product.name}</h3>
          <p className="priceSmall">\${product.price}</p>
        </div>
      </Link>
      {!compact ? <button className="quickAdd" onClick={() => addToCart(product.id)} type="button">Add</button> : null}
    </article>
  );
}

function HeroSection({
  pages,
  primaryButtonClass,
  section,
}: {
  pages: TemplatePage[];
  primaryButtonClass: string;
  section: TemplateSection;
}) {
  const settings = section.settings as Record<string, unknown>;
  const variant = styleSetting(settings.variant, 'split');
  const copy = (
    <div>
      <p className="eyebrow">{String(settings.eyebrow ?? '')}</p>
      <h1>{String(settings.title ?? '')}</h1>
      <p className="heroCopy">{String(settings.copy ?? '')}</p>
      <div className="actions">
        <Link className={primaryButtonClass} href={pathFor(pages, 'collection')}>{String(settings.cta ?? 'Shop now')}</Link>
        <Link className="button outline" href={pathFor(pages, 'about')}>View lookbook</Link>
      </div>
    </div>
  );

  if (variant === 'centered') {
    return (
      <section className={sectionClass(section, 'spacious')}>
        <div className="wrap heroCentered">
          {copy}
          <div className="productGrid grid">
            {template.products.slice(0, 3).map((product) => (
              <ProductCard addToCart={() => undefined} href={pathFor(pages, 'product')} key={product.id} product={product} setActiveProductId={() => undefined} />
            ))}
          </div>
        </div>
      </section>
    );
  }

  if (variant === 'productSpotlight') {
    const product = template.products[0];

    return (
      <section className={sectionClass(section, 'spacious')}>
        <div className="wrap heroGrid spotlight">
          <div className="heroCard" style={productImageStyle(product)}>
            <div className="floatingCard">
              <p className="eyebrow">Spotlight</p>
              <h3>{product?.name ?? 'Featured product'}</h3>
              <p className="muted">{product ? '$' + product.price + ' / ' + product.category : 'Ready to customize.'}</p>
            </div>
          </div>
          {copy}
        </div>
      </section>
    );
  }

  return (
    <section className={sectionClass(section, 'spacious')}>
      <div className="wrap heroGrid">
        {copy}
        <div className="heroCard">
          <div className="heroArt" />
          <div className="floatingCard">
            <p className="eyebrow">Featured set</p>
            <h3>Curated everyday essentials</h3>
            <p className="muted">Three-piece capsule bundle from $164.</p>
          </div>
        </div>
      </div>
    </section>
  );
}

function ProductImage({ large, product }: { large?: boolean; product?: Product }) {
  return (
    <div
      className={large ? 'productImage large' : 'productImage'}
      style={{
        backgroundImage: product?.image,
        backgroundPosition: \`\${product?.imagePositionX ?? 50}% \${product?.imagePositionY ?? 50}%\`,
        backgroundSize: \`\${product?.imageZoom ?? 100}%\`,
      }}
    />
  );
}

function productImageStyle(product?: Product) {
  return {
    backgroundImage: product?.image,
    backgroundPosition: \`\${product?.imagePositionX ?? 50}% \${product?.imagePositionY ?? 50}%\`,
    backgroundRepeat: 'no-repeat',
    backgroundSize: \`\${product?.imageZoom ?? 100}%\`,
  };
}

function SimpleListSection({ items, section, title }: { items: string[]; section: TemplateSection; title: string }) {
  return (
    <section className={sectionClass(section, 'surface')}>
      <div className="wrap">
        <h2>{title}</h2>
        <div className="grid cols3 productGrid">{items.map((item, index) => <article className="card cardBody" key={item}><p className="eyebrow">0{index + 1}</p><h3>{item}</h3><p className="muted">Editable storefront content generated from your template.</p></article>)}</div>
      </div>
    </section>
  );
}

function SummaryRow({ label, value }: { label: string; value: string }) {
  return <div className="line"><span>{label}</span><strong>{value}</strong></div>;
}

function pathFor(pages: TemplatePage[], type: PageType) {
  const page = pages.find((candidate) => candidate.type === type);
  return page ? pagePaths[page.type as PageType] : '#';
}

function headerNavLinks(pages: TemplatePage[], settings: Record<string, unknown>) {
  const navItems = structuredNavItems(settings.navItems);

  if (navItems.length > 0) {
    return navItems
      .map((item) => {
        if (item.targetType === 'url') {
          return { href: item.url, id: item.id, label: item.label, page: undefined };
        }

        const page = pages.find((candidate) => candidate.type === item.pageType);

        if (!page) {
          return null;
        }

        return { href: pagePaths[page.type as PageType] ?? '/', id: item.id, label: item.label || page.name, page };
      })
      .filter((link): link is { href: string; id: string; label: string; page?: TemplatePage } => Boolean(link));
  }

  return (['home', 'collection', 'about', 'contact'] as const)
    .filter((type) => headerLinkVisible(type, settings))
    .map((type) => {
      const page = pages.find((candidate) => candidate.type === type);

      if (!page) {
        return null;
      }

      return {
        href: pagePaths[page.type as PageType] ?? '/',
        id: page.id,
        label: headerLinkLabel(type, page, settings),
        page,
      };
    })
    .filter((link): link is { href: string; id: string; label: string; page?: TemplatePage } => Boolean(link));
}

type HeaderNavItem = {
  id: string;
  label: string;
  pageType: PageType;
  targetType: 'page' | 'url';
  url: string;
};

function structuredNavItems(value: unknown): HeaderNavItem[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((item, index) => {
      if (!item || typeof item !== 'object') {
        return null;
      }

      const navItem = item as Record<string, unknown>;
      const targetType = navItem.targetType === 'url' ? 'url' : 'page';
      const pageType = pageTypeSetting(navItem.pageType);
      const url = textSetting(navItem.url, '');
      const label = textSetting(navItem.label, targetType === 'url' ? 'Link' : pageType);

      if (targetType === 'url' && !url) {
        return null;
      }

      return {
        id: textSetting(navItem.id, \`nav-\${index}\`),
        label,
        pageType,
        targetType,
        url,
      };
    })
    .filter((item): item is HeaderNavItem => Boolean(item));
}

function pageTypeSetting(value: unknown): PageType {
  const pageTypes: PageType[] = ['home', 'collection', 'product', 'cart', 'checkout', 'about', 'contact'];
  return typeof value === 'string' && pageTypes.includes(value as PageType) ? (value as PageType) : 'home';
}

function headerLinkVisible(type: 'about' | 'collection' | 'contact' | 'home', settings: Record<string, unknown>) {
  const visibilityKeys = {
    about: 'showAboutLink',
    collection: 'showCollectionLink',
    contact: 'showContactLink',
    home: 'showHomeLink',
  };

  return settings[visibilityKeys[type]] !== false;
}

function headerLinkLabel(type: 'about' | 'collection' | 'contact' | 'home', page: TemplatePage, settings: Record<string, unknown>) {
  const labelKeys = {
    about: 'labelAbout',
    collection: 'labelCollection',
    contact: 'labelContact',
    home: 'labelHome',
  };

  return textSetting(settings[labelKeys[type]], page.name);
}

function textSetting(value: unknown, fallback: string) {
  return typeof value === 'string' && value.trim() ? value : fallback;
}

function sectionClass(section: TemplateSection, fallback: string) {
  const settings = section.settings as Record<string, unknown>;
  const background = typeof settings.background === 'string' && settings.background !== 'default' ? settings.background : fallback;
  const spacing = typeof settings.spacing === 'string' ? settings.spacing : '';
  return ['section', spacing === 'compact' ? 'compact' : spacing === 'spacious' ? 'spacious' : '', background].filter(Boolean).join(' ');
}

function buttonClass(settings: Record<string, unknown>) {
  const style = settings.buttonStyle;
  return \`button\${style === 'dark' ? ' dark' : style === 'outline' ? ' outline' : ''}\`;
}

function arraySetting(value: unknown) {
  return Array.isArray(value) ? value.map((item) => String(item)) : [];
}

function numberSetting(value: unknown, fallback: number) {
  return typeof value === 'number' && Number.isFinite(value) ? value : fallback;
}

function styleSetting(value: unknown, fallback: string) {
  return typeof value === 'string' ? value : fallback;
}
`;
}
